"use client";

import { useState, useEffect } from "react";
import { Sparkles, ImageOff, Hash } from "lucide-react";
import { StatusBadge } from "@/components/ui/status-badge";
import { Card } from "@/components/ui/card";
import { Skeleton } from "@/components/ui/skeleton";
import { EmptyState } from "@/components/ui/empty-state";
import { ErrorState } from "@/components/ui/error-state";
import { Badge } from "@/components/ui/badge";

interface Design {
  id: string;
  title: string;
  description: string | null;
  designType: string | null;
  status: string;
  images: Array<{ storageUrl: string | null; status: string; attempt: number }>;
  niche: { name: string } | null;
}

export default function DesignsPage() {
  const [designs, setDesigns] = useState<Design[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  async function loadData() {
    setLoading(true);
    setError(null);
    try {
      const res = await fetch("/api/designs");
      if (!res.ok) throw new Error(`Couldn't load designs (${res.status})`);
      const data = await res.json();
      setDesigns(data.designs ?? []);
    } catch (e) {
      setError(e instanceof Error ? e.message : "Couldn't load designs");
    } finally {
      setLoading(false);
    }
  }

  useEffect(() => { loadData(); }, []);

  if (loading) {
    return (
      <div className="space-y-6">
        <Skeleton className="h-8 w-40" />
        <div className="grid grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-3 sm:gap-4">
          {[1, 2, 3, 4, 5, 6, 7, 8].map((i) => (
            <Skeleton key={i} className="aspect-[3/4] w-full" />
          ))}
        </div>
      </div>
    );
  }

  if (error && designs.length === 0) {
    return (
      <div className="space-y-6">
        <div className="page-header">
          <h1 className="text-2xl font-bold text-fg tracking-tight">Designs</h1>
        </div>
        <ErrorState message={error} onRetry={loadData} retrying={loading} />
      </div>
    );
  }

  return (
    <div className="space-y-6 animate-fade-in-up">
      <div className="page-header">
        <h1 className="text-2xl font-bold text-fg tracking-tight">Designs</h1>
        <p className="text-sm text-fg-subtle mt-1">
          {designs.length > 0
            ? `${designs.length} AI-generated design${designs.length === 1 ? "" : "s"}.`
            : "Concepts generated by the pipeline will appear here."}
        </p>
      </div>

      {designs.length === 0 ? (
        <Card>
          <EmptyState
            icon={<Sparkles className="h-6 w-6" />}
            title="No designs yet"
            description="Once a niche is approved and the pipeline runs step 3, generated concepts will show up here."
          />
        </Card>
      ) : (
        <div className="grid grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-3 sm:gap-4">
          {designs.map((design, idx) => (
            <Card
              key={design.id}
              className="overflow-hidden group animate-fade-in-up"
              hover
              style={{ animationDelay: `${Math.min(idx * 30, 360)}ms` }}
            >
              <div className="aspect-square bg-surface-2 relative overflow-hidden">
                {(() => {
                  const displayImage = design.images.find((img) => img.storageUrl);
                  return displayImage?.storageUrl ? (
                    // eslint-disable-next-line @next/next/no-img-element
                    <img
                      src={displayImage.storageUrl}
                      alt={design.title}
                      className="w-full h-full object-cover transition-transform duration-500 group-hover:scale-105"
                    />
                  ) : (
                    <div className="w-full h-full flex flex-col items-center justify-center text-fg-faint gap-2">
                      <ImageOff className="h-6 w-6" />
                      <span className="text-[10px] uppercase tracking-wider">No image</span>
                    </div>
                  );
                })()}
                <div className="absolute top-2 right-2">
                  <StatusBadge status={design.status} />
                </div>
              </div>
              <div className="p-3 space-y-1.5">
                <h3 className="font-medium text-sm text-fg truncate" title={design.title}>{design.title}</h3>
                <div className="flex items-center gap-2 flex-wrap">
                  {design.designType && (
                    <Badge tone="brand">{design.designType}</Badge>
                  )}
                </div>
                {design.niche && (
                  <p className="text-xs text-fg-subtle truncate inline-flex items-center gap-1">
                    <Hash className="h-3 w-3 text-fg-faint" />
                    {design.niche.name}
                  </p>
                )}
              </div>
            </Card>
          ))}
        </div>
      )}
    </div>
  );
}
